//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfariDB_Tipo
    {
        public int Id { get; set; }
        public string UUID { get; set; }
        public string Repository { get; set; }
        public string FolderName { get; set; }
        public string UserKey { get; set; }
        public Nullable<System.DateTime> UtcCreationDate { get; set; }
        public Nullable<System.DateTime> UtcLastModificationDate { get; set; }
        public Nullable<bool> Published { get; set; }
        public string OriginalUUID { get; set; }
        public string SchemaName { get; set; }
        public string ParentFolder { get; set; }
        public string ParentUUID { get; set; }
        public string UserId { get; set; }
        public string OriginalRepository { get; set; }
        public string OriginalFolder { get; set; }
        public Nullable<bool> IsLocalized { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Nombre { get; set; }
    }
}
