//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public int AnuncioId { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public string Estado { get; set; }
        public string Url { get; set; }
        public int Prioridad { get; set; }
        public int CantidadClic { get; set; }
        public int UsuarioId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
