//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoIngreso
    {
        public int ArchivoIngresoId { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IngresoId { get; set; }
    
        public virtual Ingreso Ingreso { get; set; }
    }
}
