//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceUnidadTiempoEdificio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BalanceUnidadTiempoEdificio()
        {
            this.Leyenda = new HashSet<Leyenda>();
        }
    
        public int BalanceUnidadTiempoEdificioId { get; set; }
        public int EdificioId { get; set; }
        public int UnidadDeTiempoId { get; set; }
        public decimal IngresosTotalesMes { get; set; }
        public decimal GastosTotalesMes { get; set; }
        public decimal SaldoMes { get; set; }
        public decimal SaldoAcumulado { get; set; }
        public System.DateTime FechaDeActualizacion { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leyenda> Leyenda { get; set; }
    }
}
