//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteCorretaje
    {
        public int ClienteCorretajeId { get; set; }
        public string TipoServicio { get; set; }
        public string TipoInmueble { get; set; }
        public string Estado { get; set; }
        public string Direccion { get; set; }
        public string Distrito { get; set; }
        public string Area { get; set; }
        public string Dormitorios { get; set; }
        public string Estacionamientos { get; set; }
        public string Deposito { get; set; }
        public string Antiguedad { get; set; }
        public string CantidadPiso { get; set; }
        public string Precio { get; set; }
        public string CostoMantenimiento { get; set; }
        public string Cliente { get; set; }
        public string Numero { get; set; }
        public string Correo { get; set; }
        public string Otros { get; set; }
        public string CantidadInmuebles { get; set; }
    }
}
