//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComisionAFP
    {
        public int ComisionAFPId { get; set; }
        public int AFPId { get; set; }
        public int TipoDescuentoId { get; set; }
        public decimal Comision { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual TipoDescuento TipoDescuento { get; set; }
    }
}
