//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaComun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuotaComun()
        {
            this.GastoCuotaComun = new HashSet<GastoCuotaComun>();
        }
    
        public int CuotaComunId { get; set; }
        public int EdificioId { get; set; }
        public int UnidadTiempoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal TotalMontoAgua { get; set; }
        public decimal TotalAreaComun { get; set; }
        public decimal TotalAlcantarillado { get; set; }
        public decimal TotalCargoFijo { get; set; }
        public decimal SaldoMes { get; set; }
        public bool Pagado { get; set; }
        public decimal TotalOtrosGastos { get; set; }
        public string Estado { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoCuotaComun> GastoCuotaComun { get; set; }
    }
}
