//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoEdificio
    {
        public int DatoEdificioId { get; set; }
        public int EdificioId { get; set; }
        public string Tipo { get; set; }
        public string Dato { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> UnidadTiempoId { get; set; }
        public bool AplicaMantenimiento { get; set; }
        public Nullable<bool> EsRealizado { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
