//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleGasto
    {
        public int DetalleGastoId { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
        public int GastoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Pagado { get; set; }
        public bool Ordinario { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual Gasto Gasto { get; set; }
    }
}
