//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edificio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edificio()
        {
            this.ArchivoCorrecionEdificio = new HashSet<ArchivoCorrecionEdificio>();
            this.ArchivoTrabajador = new HashSet<ArchivoTrabajador>();
            this.BalanceUnidadTiempoEdificio = new HashSet<BalanceUnidadTiempoEdificio>();
            this.Cronograma = new HashSet<Cronograma>();
            this.CuotaComun = new HashSet<CuotaComun>();
            this.DatoEdificio = new HashSet<DatoEdificio>();
            this.Departamento = new HashSet<Departamento>();
            this.EmailValidacion = new HashSet<EmailValidacion>();
            this.EstadoCuentaBancario = new HashSet<EstadoCuentaBancario>();
            this.Gasto = new HashSet<Gasto>();
            this.Ingreso = new HashSet<Ingreso>();
            this.Inspeccion = new HashSet<Inspeccion>();
            this.ItemActa = new HashSet<ItemActa>();
            this.MenuPropietarioEdificio = new HashSet<MenuPropietarioEdificio>();
            this.Noticia = new HashSet<Noticia>();
            this.PermisoEdificio = new HashSet<PermisoEdificio>();
            this.PlanillaR = new HashSet<PlanillaR>();
            this.ReciboMes = new HashSet<ReciboMes>();
            this.ReporteEdificioUnidadTiempo = new HashSet<ReporteEdificioUnidadTiempo>();
            this.Trabajador = new HashSet<Trabajador>();
            this.Visita = new HashSet<Visita>();
        }
    
        public int EdificioId { get; set; }
        public string Acronimo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Referencia { get; set; }
        public string Estado { get; set; }
        public Nullable<int> UDepartamentoId { get; set; }
        public Nullable<int> NroDepartamentos { get; set; }
        public Nullable<int> UProvinciaId { get; set; }
        public Nullable<int> UDistritoId { get; set; }
        public decimal MontoCuota { get; set; }
        public string FactorAreaComun { get; set; }
        public string FactorAlcantarillado { get; set; }
        public string FactorCargoFijo { get; set; }
        public string Representante { get; set; }
        public int Identificador { get; set; }
        public int CantidadReporte { get; set; }
        public Nullable<decimal> PMora { get; set; }
        public string NroCuenta { get; set; }
        public string NormasConvivencia { get; set; }
        public decimal SaldoAcumulado { get; set; }
        public string TipoMora { get; set; }
        public int DiaEmisionCuota { get; set; }
        public Nullable<int> DesfaseRecibos { get; set; }
        public string EmailEncargado { get; set; }
        public Nullable<decimal> SaldoAnteriorHistorico { get; set; }
        public string Firma { get; set; }
        public string NombreEncargado { get; set; }
        public Nullable<decimal> PresupuestoMensual { get; set; }
        public string NombrePago { get; set; }
        public string MensajeMora { get; set; }
        public Nullable<int> TipoInmuebleId { get; set; }
        public Nullable<int> ReciboUnidadTiempoId { get; set; }
        public Nullable<int> DiaMora { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> SaldoAnteriorUnidadTiempo { get; set; }
        public Nullable<bool> UsarInquilinoCCPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoCorrecionEdificio> ArchivoCorrecionEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoTrabajador> ArchivoTrabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalanceUnidadTiempoEdificio> BalanceUnidadTiempoEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cronograma> Cronograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuotaComun> CuotaComun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatoEdificio> DatoEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamento { get; set; }
        public virtual TipoInmueble TipoInmueble { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailValidacion> EmailValidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuentaBancario> EstadoCuentaBancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemActa> ItemActa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuPropietarioEdificio> MenuPropietarioEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticia> Noticia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoEdificio> PermisoEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaR> PlanillaR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboMes> ReciboMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteEdificioUnidadTiempo> ReporteEdificioUnidadTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajador> Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visita { get; set; }
    }
}
