//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gasto()
        {
            this.ArchivoGasto = new HashSet<ArchivoGasto>();
            this.DetalleGasto = new HashSet<DetalleGasto>();
        }
    
        public int GastoId { get; set; }
        public int EdificioId { get; set; }
        public string Estado { get; set; }
        public int UnidadTiempoId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<decimal> SaldoMes { get; set; }
        public Nullable<decimal> CuentasPorCobrarO { get; set; }
        public Nullable<decimal> CuentasPorCobrarE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoGasto> ArchivoGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleGasto> DetalleGasto { get; set; }
        public virtual Edificio Edificio { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
