//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquilino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquilino()
        {
            this.PropietarioInquilino = new HashSet<PropietarioInquilino>();
        }
    
        public int InquilinoId { get; set; }
        public int PropietarioId { get; set; }
        public string Nombres { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Estado { get; set; }
        public string Contacto { get; set; }
        public string Dni { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<bool> MostrarRUC { get; set; }
    
        public virtual Propietario Propietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropietarioInquilino> PropietarioInquilino { get; set; }
    }
}
