//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public int InspeccionId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Pregunta1 { get; set; }
        public int Pregunta2 { get; set; }
        public int Pregunta3 { get; set; }
        public int Pregunta4 { get; set; }
        public int Pregunta5 { get; set; }
        public int Pregunta6 { get; set; }
        public int Pregunta7 { get; set; }
        public int Pregunta8 { get; set; }
        public int Pregunta9 { get; set; }
        public int Pregunta10 { get; set; }
        public int Pregunta11 { get; set; }
        public int Pregunta12 { get; set; }
        public int Pregunta13 { get; set; }
        public int Pregunta14 { get; set; }
        public int Pregunta15 { get; set; }
        public int Pregunta16 { get; set; }
        public int Pregunta17 { get; set; }
        public int Pregunta18 { get; set; }
        public int Pregunta19 { get; set; }
        public int Pregunta20 { get; set; }
        public int Pregunta21 { get; set; }
        public int Pregunta22 { get; set; }
        public int Pregunta23 { get; set; }
        public int Pregunta24 { get; set; }
        public int Pregunta25 { get; set; }
        public int Pregunta26 { get; set; }
        public int Pregunta27 { get; set; }
        public int Pregunta28 { get; set; }
        public int Pregunta29 { get; set; }
        public int Pregunta30 { get; set; }
        public int Pregunta31 { get; set; }
        public int Pregunta32 { get; set; }
        public int Pregunta33 { get; set; }
        public int Pregunta34 { get; set; }
        public int Pregunta35 { get; set; }
        public int Pregunta36 { get; set; }
        public string Enunciado1 { get; set; }
        public string Enunciado2 { get; set; }
        public string Enunciado3 { get; set; }
        public string Enunciado4 { get; set; }
        public string Enunciado5 { get; set; }
        public string Enunciado6 { get; set; }
        public string Enunciado7 { get; set; }
        public string Enunciado8 { get; set; }
        public string Enunciado9 { get; set; }
        public string Observaciones { get; set; }
        public int EdificioId { get; set; }
    
        public virtual Edificio Edificio { get; set; }
    }
}
