//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leyenda
    {
        public int LeyendaId { get; set; }
        public string Descripcion { get; set; }
        public int Numero { get; set; }
        public int BalanceUnidadTiempoEdificioId { get; set; }
    
        public virtual BalanceUnidadTiempoEdificio BalanceUnidadTiempoEdificio { get; set; }
    }
}
