//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_92747_bitportalEntities : DbContext
    {
        public DB_92747_bitportalEntities()
            : base("name=DB_92747_bitportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AfariDB___ContentCategory> AfariDB___ContentCategory { get; set; }
        public virtual DbSet<AfariDB_Categoria> AfariDB_Categoria { get; set; }
        public virtual DbSet<AfariDB_Cliente> AfariDB_Cliente { get; set; }
        public virtual DbSet<AfariDB_Departamento> AfariDB_Departamento { get; set; }
        public virtual DbSet<AfariDB_Desuscribirse> AfariDB_Desuscribirse { get; set; }
        public virtual DbSet<AfariDB_Distrito> AfariDB_Distrito { get; set; }
        public virtual DbSet<AfariDB_Edificio> AfariDB_Edificio { get; set; }
        public virtual DbSet<AfariDB_InmueblesServicios> AfariDB_InmueblesServicios { get; set; }
        public virtual DbSet<AfariDB_Lugar> AfariDB_Lugar { get; set; }
        public virtual DbSet<AfariDB_Provincia> AfariDB_Provincia { get; set; }
        public virtual DbSet<AfariDB_Tipo> AfariDB_Tipo { get; set; }
        public virtual DbSet<VehDB___ContentCategory> VehDB___ContentCategory { get; set; }
        public virtual DbSet<VehDB_Categoria> VehDB_Categoria { get; set; }
        public virtual DbSet<VehDB_Departamento> VehDB_Departamento { get; set; }
        public virtual DbSet<VehDB_Desuscribirse> VehDB_Desuscribirse { get; set; }
        public virtual DbSet<VehDB_Distrito> VehDB_Distrito { get; set; }
        public virtual DbSet<VehDB_Edificio> VehDB_Edificio { get; set; }
        public virtual DbSet<VehDB_Lugar> VehDB_Lugar { get; set; }
        public virtual DbSet<VehDB_Provincia> VehDB_Provincia { get; set; }
        public virtual DbSet<VehDB_Tipo> VehDB_Tipo { get; set; }
    }
}
