//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int NoticiaId { get; set; }
        public string Titulo { get; set; }
        public string Sumilla { get; set; }
        public string Detalle { get; set; }
        public string Estado { get; set; }
        public int EdificioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Edificio Edificio { get; set; }
    }
}
