//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaR
    {
        public int PlanillaRId { get; set; }
        public string RutaExcel { get; set; }
        public string RutaPDF { get; set; }
        public int UnidadTiempoId { get; set; }
        public int EdificioId { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
