//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaQuincena
    {
        public int PlanillaQuincenaId { get; set; }
        public Nullable<decimal> BonoPorMovilidad { get; set; }
        public Nullable<decimal> Bonificacion { get; set; }
        public Nullable<decimal> TotalQuincena { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public int UnidadTiempoId { get; set; }
        public int TrabajadorId { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
