//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int PlanillaId { get; set; }
        public int TrabajadorId { get; set; }
        public int UnidadTiempoId { get; set; }
        public Nullable<decimal> HorasExtras { get; set; }
        public decimal Feriado { get; set; }
        public decimal AdelantoQuincena { get; set; }
        public decimal SegundaQuincena { get; set; }
        public decimal ESSALUD { get; set; }
        public decimal AporteObligatorio { get; set; }
        public decimal PrimaSeguro { get; set; }
        public decimal ComisionAFP { get; set; }
        public decimal TotalDescuentos { get; set; }
        public decimal SueldoTotalNeto { get; set; }
        public decimal SegundaQuincenaNeto { get; set; }
        public decimal CTSMes { get; set; }
        public decimal ReemplazoVacaciones { get; set; }
        public Nullable<decimal> HorasExtras25 { get; set; }
        public Nullable<decimal> HorasExtras35 { get; set; }
        public Nullable<decimal> MontoFeriados { get; set; }
        public Nullable<decimal> DescuenoAusencia { get; set; }
        public Nullable<decimal> AumentoReemplazo { get; set; }
        public Nullable<decimal> TotalMes { get; set; }
        public Nullable<decimal> MontoHorasExtras25 { get; set; }
        public Nullable<decimal> MontoHorasExtras35 { get; set; }
        public Nullable<decimal> GratificacionesMes { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
        public virtual UnidadTiempo UnidadTiempo { get; set; }
    }
}
