//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropietarioInquilino
    {
        public int PropietarioInquilinoId { get; set; }
        public int PropietarioId { get; set; }
        public int InquilinoId { get; set; }
    
        public virtual Inquilino Inquilino { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
