//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propietario()
        {
            this.DepartamentoHistorico = new HashSet<DepartamentoHistorico>();
            this.DepartamentoPropietario = new HashSet<DepartamentoPropietario>();
            this.Inquilino = new HashSet<Inquilino>();
            this.PropietarioInquilino = new HashSet<PropietarioInquilino>();
        }
    
        public int PropietarioId { get; set; }
        public string TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Cargo { get; set; }
        public string Estado { get; set; }
        public int DepartamentoId { get; set; }
        public string Email { get; set; }
        public string Poseedor { get; set; }
        public string ParentescoTitular { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public Nullable<bool> MostrarRUC { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartamentoHistorico> DepartamentoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartamentoPropietario> DepartamentoPropietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquilino> Inquilino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropietarioInquilino> PropietarioInquilino { get; set; }
    }
}
