//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIVEHEntities : DbContext
    {
        public SIVEHEntities()
            : base("name=SIVEHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AFP> AFP { get; set; }
        public virtual DbSet<Anuncio> Anuncio { get; set; }
        public virtual DbSet<ArchivoCorrecionEdificio> ArchivoCorrecionEdificio { get; set; }
        public virtual DbSet<ArchivoGasto> ArchivoGasto { get; set; }
        public virtual DbSet<ArchivoIngreso> ArchivoIngreso { get; set; }
        public virtual DbSet<ArchivoTrabajador> ArchivoTrabajador { get; set; }
        public virtual DbSet<BalanceUnidadTiempoEdificio> BalanceUnidadTiempoEdificio { get; set; }
        public virtual DbSet<ComisionAFP> ComisionAFP { get; set; }
        public virtual DbSet<Cronograma> Cronograma { get; set; }
        public virtual DbSet<CuotaComun> CuotaComun { get; set; }
        public virtual DbSet<DatoEdificio> DatoEdificio { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DepartamentoHistorico> DepartamentoHistorico { get; set; }
        public virtual DbSet<DepartamentoPropietario> DepartamentoPropietario { get; set; }
        public virtual DbSet<DetalleCronograma> DetalleCronograma { get; set; }
        public virtual DbSet<DetalleGasto> DetalleGasto { get; set; }
        public virtual DbSet<DetalleIngreso> DetalleIngreso { get; set; }
        public virtual DbSet<DetalleMensualidad> DetalleMensualidad { get; set; }
        public virtual DbSet<DetalleQuincena> DetalleQuincena { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<EmailValidacion> EmailValidacion { get; set; }
        public virtual DbSet<EstadoCuentaBancario> EstadoCuentaBancario { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<GastoCuotaComun> GastoCuotaComun { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<Inquilino> Inquilino { get; set; }
        public virtual DbSet<Inspeccion> Inspeccion { get; set; }
        public virtual DbSet<ItemActa> ItemActa { get; set; }
        public virtual DbSet<Leyenda> Leyenda { get; set; }
        public virtual DbSet<MenuPropietarioEdificio> MenuPropietarioEdificio { get; set; }
        public virtual DbSet<NivelEstado> NivelEstado { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<PermisoEdificio> PermisoEdificio { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<PlanillaQuincena> PlanillaQuincena { get; set; }
        public virtual DbSet<PlanillaR> PlanillaR { get; set; }
        public virtual DbSet<Propietario> Propietario { get; set; }
        public virtual DbSet<PropietarioInquilino> PropietarioInquilino { get; set; }
        public virtual DbSet<ReciboMes> ReciboMes { get; set; }
        public virtual DbSet<ReporteEdificioUnidadTiempo> ReporteEdificioUnidadTiempo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDescuento> TipoDescuento { get; set; }
        public virtual DbSet<TipoInmueble> TipoInmueble { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
        public virtual DbSet<UDepartamento> UDepartamento { get; set; }
        public virtual DbSet<UDistrito> UDistrito { get; set; }
        public virtual DbSet<UnidadTiempo> UnidadTiempo { get; set; }
        public virtual DbSet<UnidadTiempoReciboDepartamento> UnidadTiempoReciboDepartamento { get; set; }
        public virtual DbSet<UProvincia> UProvincia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<ConsumoIndividual> ConsumoIndividual { get; set; }
        public virtual DbSet<Cuota> Cuota { get; set; }
    }
}
