//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Planilla = new HashSet<Planilla>();
            this.PlanillaQuincena = new HashSet<PlanillaQuincena>();
        }
    
        public int TrabajadorId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string AntecedentesPoliciales { get; set; }
        public string PartidaNacimiento { get; set; }
        public string Foto { get; set; }
        public string Cargo { get; set; }
        public string CUSSP { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public int EdificioId { get; set; }
        public string Modalidad { get; set; }
        public decimal SueldoBase { get; set; }
        public string Estado { get; set; }
        public Nullable<int> AFPId { get; set; }
        public Nullable<decimal> MontoHoras25 { get; set; }
        public Nullable<decimal> MontoHoras35 { get; set; }
        public Nullable<decimal> MontoFeriado { get; set; }
        public Nullable<decimal> AdelantoQuincena { get; set; }
        public string ComisionFlujo { get; set; }
        public Nullable<int> DetalleQuincenaId { get; set; }
        public Nullable<int> DetalleMensualidadId { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual DetalleMensualidad DetalleMensualidad { get; set; }
        public virtual DetalleQuincena DetalleQuincena { get; set; }
        public virtual Edificio Edificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planilla> Planilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaQuincena> PlanillaQuincena { get; set; }
    }
}
