//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadTiempo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadTiempo()
        {
            this.ArchivoCorrecionEdificio = new HashSet<ArchivoCorrecionEdificio>();
            this.ArchivoTrabajador = new HashSet<ArchivoTrabajador>();
            this.BalanceUnidadTiempoEdificio = new HashSet<BalanceUnidadTiempoEdificio>();
            this.CuotaComun = new HashSet<CuotaComun>();
            this.DatoEdificio = new HashSet<DatoEdificio>();
            this.Edificio = new HashSet<Edificio>();
            this.EstadoCuentaBancario = new HashSet<EstadoCuentaBancario>();
            this.Gasto = new HashSet<Gasto>();
            this.Ingreso = new HashSet<Ingreso>();
            this.ItemActa = new HashSet<ItemActa>();
            this.Planilla = new HashSet<Planilla>();
            this.PlanillaQuincena = new HashSet<PlanillaQuincena>();
            this.PlanillaR = new HashSet<PlanillaR>();
            this.ReciboMes = new HashSet<ReciboMes>();
            this.ReporteEdificioUnidadTiempo = new HashSet<ReporteEdificioUnidadTiempo>();
            this.UnidadTiempoReciboDepartamento = new HashSet<UnidadTiempoReciboDepartamento>();
            this.Cuota = new HashSet<Cuota>();
        }
    
        public int UnidadTiempoId { get; set; }
        public string Descripcion { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public bool EsActivo { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoCorrecionEdificio> ArchivoCorrecionEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoTrabajador> ArchivoTrabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalanceUnidadTiempoEdificio> BalanceUnidadTiempoEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuotaComun> CuotaComun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatoEdificio> DatoEdificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edificio> Edificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuentaBancario> EstadoCuentaBancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemActa> ItemActa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planilla> Planilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaQuincena> PlanillaQuincena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaR> PlanillaR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboMes> ReciboMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteEdificioUnidadTiempo> ReporteEdificioUnidadTiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadTiempoReciboDepartamento> UnidadTiempoReciboDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuota { get; set; }
    }
}
