//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehDB___ContentCategory
    {
        public int Id { get; set; }
        public string UUID { get; set; }
        public string CategoryFolder { get; set; }
        public string CategoryUUID { get; set; }
    }
}
