//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaCorretaje
    {
        public int VisitaCorretajeId { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string Tipo { get; set; }
        public decimal Precio { get; set; }
        public string Moneda { get; set; }
        public string NombreCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Estado { get; set; }
        public string Firma { get; set; }
        public string Correo { get; set; }
    }
}
