//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEH.Intranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int VisitaId { get; set; }
        public int UsuarioId { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int DepartamentoId { get; set; }
        public int EdificioId { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Edificio Edificio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
